version: "3.8"

services:
  api:
    build: ./
    environment:
      MONGO_URL: ${MONGO_URL}
      CRYPT_TOK: ${CRYPT_TOK}
    ports:
      - "8080:8080"

  app:
    image: izimio/kdb-ui:taker-academy-ui-1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - api